# Generated by Django 4.2.4 on 2024-02-06 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('description', models.CharField(default='Enter Description Here...', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('square_footage', models.CharField(max_length=200)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('home_type', models.CharField(max_length=200)),
                ('description', models.CharField(default='Enter Description Here...', max_length=1000)),
                ('google_maps', models.CharField(default='Enter Link Here...', max_length=1000)),
                ('furnitures', models.ManyToManyField(to='main_app.furniture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('square_footage', models.CharField(max_length=200)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('home_type', models.CharField(max_length=200)),
                ('google_maps', models.CharField(default='Enter Link Here...', max_length=1000)),
                ('description', models.CharField(default='Enter Description Here...', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tour date')),
                ('time', models.CharField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.home')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('description', models.CharField(default='Enter your review here...', max_length=1500)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.home')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='RentTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tour date')),
                ('time', models.CharField()),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rent')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='RentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('description', models.CharField(default='Enter your review here...', max_length=1500)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rent')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='RentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rent')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.home')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('description', models.CharField(default='Enter your review here...', max_length=1500)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.furniture')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='FurniturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.furniture')),
            ],
        ),
    ]
