# Generated by Django 4.2.4 on 2023-08-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('square_footage', models.CharField(max_length=200)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('home_type', models.CharField(max_length=200)),
            ],
        ),
    ]
