# Generated by Django 4.2.4 on 2023-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('square_footage', models.CharField(max_length=200)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('home_type', models.CharField(max_length=200)),
            ],
        ),
    ]
