# Generated by Django 4.2.4 on 2023-08-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.CharField(max_length=100)),
            ],
        ),
    ]
