# Generated by Django 4.2.4 on 2023-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_furniture'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='furnitures',
            field=models.ManyToManyField(to='main_app.furniture'),
        ),
    ]
