# Generated by Django 4.2.4 on 2023-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_home_furnitures'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='description',
            field=models.CharField(default='Enter Description Here...', max_length=1000),
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.CharField(default='Enter Description Here...', max_length=1000),
        ),
        migrations.AddField(
            model_name='rent',
            name='description',
            field=models.CharField(default='Enter Description Here...', max_length=1000),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='length',
            field=models.IntegerField(),
        ),
    ]
