# Generated by Django 4.2.4 on 2023-08-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_furniture_height_alter_furniture_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1', 'Poor'), ('2', 'Moderately Poor'), ('3', 'Average'), ('4', 'Moderately Impressive'), ('5', 'Impressive')])),
                ('description', models.CharField(default='Enter your review here...', max_length=1500)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.home')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
