# Generated by Django 4.2.4 on 2023-08-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_review_rating_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tour',
            new_name='home',
        ),
    ]
