# Generated by Django 4.2.4 on 2023-08-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_tour_options_rename_tour_tour_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.CharField(),
        ),
    ]
