# Generated by Django 4.2.4 on 2023-08-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_cat_photo_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.CreateModel(
            name='RentTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tour date')),
                ('time', models.CharField()),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rent')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='RentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('description', models.CharField(default='Enter your review here...', max_length=1500)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rent')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='RentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rent')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('description', models.CharField(default='Enter your review here...', max_length=1500)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.furniture')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='FurniturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.furniture')),
            ],
        ),
    ]
