# Generated by Django 4.2.4 on 2023-08-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_home_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='google_maps',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
