# Generated by Django 4.2.4 on 2023-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_home_google_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='google_maps',
            field=models.CharField(default='Enter Link Here...', max_length=1000),
        ),
        migrations.AlterField(
            model_name='home',
            name='google_maps',
            field=models.CharField(default='Enter Link Here...', max_length=1000),
        ),
    ]
